Add replay command
anoadragon453/busty pull request #197
Opened 2023-10-26 00:44 UTC by Cephian

Add replay command, which may or may not incidentally help recover from crashes, not that we ever have those or anything.

Done by changing the for-loop for songs to a globally index which is incremented each time, and which can be manipulated when playback is cancelled. Also removed async from BustController stop function since idk why it was there.

Merged code for skip and replay. Could even merge in stop if we just make stop a "skip" to track index of len(bust_content)? But idk if that's confusing. Have tested skip/replay/stop and they all work fine at both index 0 and index nonzero. Made code generic so implementing a /skip <num> with a number argument would be ez. We can give it to an intern.

2023-10-30 23:03 UTC, anoadragon453 requested changes
Looks good overall, and a very helpful addition.

Pray we never have to use it :angel:

2023-10-30 23:04 UTC, anoadragon453 commented
> Could even merge in stop if we just make stop a "skip" to track index of len(bust_content)?

Hmm, Busty would then print out the normal bust-ending message rather than her custom stop message. I'm not sure if we want that change?

2023-11-07 02:05 UTC, Cephian commented on src/bust.py
> +        self.playing_index = skip_count
wrong.

2023-11-07 02:06 UTC, anoadragon453 approved these changes
We decided not to do the stop thing.

2023-11-07 02:07 UTC, merged