Show total length of songs after bust
anoadragon453/busty pull request #94
Opened 2022-03-16 01:43 UTC by Cephian

Closes #69.

Sums the total lengths of all submissions to show at the end. This branch was tested in production at Busty's 6 (and it worked!)
![image](https://user-images.githubusercontent.com/6956898/158499567-8425abaf-097d-4bc7-b83b-1de6234c0cb2.png)

The actual calculation is occurs when `!list` is called, but this doesn't increase list command latency since it is calculated after messages are sent and pinned.

2022-03-17 18:06 UTC, Cephian commented
I'm not totally sure why GitHub still says this branch has a merge conflict, but the "conflict" would be very easy to solve manually in the GitHub interface when merging, so consider this ready to merge.

2022-03-19 08:37 UTC, anoadragon453 commented
@Cephian I fixed the conflict by doing:

```
git checkout total_len
git pull origin main
<fix conflicts>
git add -u && git commit
```

2022-03-19 09:22 UTC, anoadragon453 requested changes
A few small changes, but overall looks pretty good!

2022-03-19 09:22 UTC, anoadragon453 commented on main.py
> +        return None
`return None` could be extracted from both exception cases.

2022-03-19 09:22 UTC, anoadragon453 commented on main.py
> +# Total length of all songs
```suggestion
# Total length of all songs in seconds
```

2022-03-19 09:22 UTC, anoadragon453 commented on main.py
> +        )
What do you think about putting the "total length" text at the bottom of the end message instead?

2022-03-19 22:24 UTC, Cephian commented on main.py
> +        audio = MutagenFile(filename)
If we do this it should be in a separate PR. I'd also want to see if it's doing things like storing the entire tag data (including all cover images) in the object which would increase our memory usage alot. At the very least, we are definitely making separate mutagen calls for both length and tag data when `!list`ing, and separate calls for both cover art and tag data when playing. which could probably be refactored and combined.

2022-03-28 21:26 UTC, anoadragon453 approved these changes
lgtm!

2022-03-28 21:29 UTC, merged